name: 'stack'
description: A package for stack data structure. have the push, pop, size, length, and top functionalities.
version: 0.1.1
homepage: https://github.com/ammaratef45/dart_stack

environment:
  sdk: ">=1.24.0 <3.0.0"
dev_dependencies:
  test: '<2.0.0'
  test_coverage: ^0.2.0
