version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: gableroux/flutter
    steps:
      - checkout
      - run: pub get && pub run test_coverage
      - codecov/upload:
          file: 'coverage/lcov.info'
